# Generated by Django 4.2.3 on 2023-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.TextField()),
                ('video_url', models.TextField()),
                ('refid', models.CharField(max_length=300)),
            ],
        ),
    ]
